name: Tests

on:
  push:
  pull_request:

jobs:
  run_tests:
    name: Test weathergen
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Test the code
        run: |
          set -vxuo pipefail
          pytest -s -vv