name: Tests

on:
  push:
  pull_request:

jobs:
  run_tests:
    name: Test weathergen
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Install dependencies with pip
        run: |
          pip install --upgrade pip wheel
          pip install -v .
          pip list

      - name: Test the code
        run: |
          pip install pytest
          set -vxuo pipefail
          pytest -s -vv